export const PulsaData = [
  {
    id: 1,
    initialName: "20",
    Brand: "Telkomsel",
    Min: "Min. Buy Rp 20.000",
    Discount: "5% Discount",
    destination: "Home",
  },
  {
    id: 2,
    initialName: "20",
    Brand: "XL",
    Min: "Min. Buy 100.000",
    Discount: "20% Discount",
    destination: "Home",
  },
  {
    id: 3,
    initialName: "20",
    Brand: "3",
    Min: "Min. Buy 100.000",
    Discount: "20% Discount",
    destination: "Home",
  },
  {
    id: 4,
    initialName: "50",
    Brand: "Simpati",
    Min: "Min. Buy 100.000",
    Discount: "20% Discount",
    destination: "Home",
  },
  {
    id: 5,
    initialName: "20",
    Brand: "XL",
    Min: "Min. Buy 100.000",
    Discount: "20% Discount",
    destination: "Home",
  },
  {
    id: 6,
    initialName: "20",
    Brand: "XL",
    Min: "Min. Buy 100.000",
    Discount: "20% Discount",
    destination: "Home",
  },
  {
    id: 7,
    initialName: "20",
    Brand: "XL",
    Min: "Min. Buy 100.000",
    Discount: "20% Discount",
    destination: "Home",
  },
  // Add more objects for additional product data
];
