export const TokenData = [
  {
    id: 1,
    initialName: "20",
    userName: "Burger King",
    price: "20",
    expDate: "20%",
    destination: "Home",
  },
  {
    id: 2,
    initialName: "150",
    userName: "Dairy Queen",
    price: "150",
    expDate: "80%",
    destination: "Point",
  },
  {
    id: 3,
    initialName: "150",
    userName: "Business Plan",
    price: "123.45",
    expDate: "150 Mbps",
    destination: "Point",
  },
  {
    id: 4,
    initialName: "150",
    userName: "Business Plan",
    price: "123.45",
    expDate: "150 Mbps",
    destination: "Point",
  },
  {
    id: 5,
    initialName: "150",
    userName: "Business Plan",
    price: "123.45",
    expDate: "150 Mbps",
    destination: "Point",
  },
  {
    id: 6,
    initialName: "150",
    userName: "Business Plan",
    price: "123.45",
    expDate: "150 Mbps",
    destination: "Point",
  },
  {
    id: 7,
    initialName: "150",
    userName: "Business Plan",
    price: "123.45",
    expDate: "150 Mbps",
    destination: "Point",
  },
  {
    id: 8,
    initialName: "150",
    userName: "Business Plan",
    price: "123.45",
    expDate: "150 Mbps",
    destination: "Point",
  },
  // Add more objects for additional product data
];
